### ISSUE TITLE
Add Add-To-Cart icon

### ISSUE THREAD

**Issue by shahzad713** [Maxed-Store/e-store-react#10]
Add an 'Add to Cart' icon in the navbar after the login button. When clicked, it should show an alert.
![Screenshot from 2023-12-31 16-31-14](https://github.com/Maxed-Store/e-store-react/assets/99446843/ac89659f-f8f5-4fdc-b6c7-2dc4a57d4e92)

The icon should be something like this:
![Screenshot from 2023-12-31 16-29-21](https://github.com/Maxed-Store/e-store-react/assets/99446843/19b29adc-b47c-44b4-b575-772e6f090c8c)

**Comment by umerfarok** [comment]
Excellent Work!

**Comment by shahzad713** [comment]
@umerfarok can you please create more new issues and assign those to Team

**Comment by Bilal713** [comment]
[image: image.png] your challenge has been completed now

your challenge has been completed now

**Comment by Bilal713** [comment]
thank you
